
# Project information
site_name: My Docs
site_url: https://easy-quest.github.io/web/
site_author: Easy Quest
# site_description: >-
#   Create a branded static site from a set of Markdown files to host the
#   documentation of your Open Source or commercial project – customizable,
#   searchable, mobile-friendly, 40+ languages

# Repository
repo_name: easy-quest/web
repo_url: https://github.com/easy-quest/web
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 - 2022 Easy Quest

# Configuration
theme:
  name: material
  custom_dir: overrides

  # Static files
  static_templates:
    - 404.html

  # Не включайте JavaScript MKDOCS
  # include_search_page: false
  # search_index_only: true

  # Значения по умолчанию, взятые из mkdocs_theme.yml
  language: ru
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: purple
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/squidfunk