
# Project information
site_name: My Docs
site_url: https://easy-quest.github.io/web/



# Configuration
theme:
  name: material
  custom_dir: overrides

  # Static files
  static_templates:
    - 404.html

  # Не включайте JavaScript MKDOCS
  # include_search_page: false
  # search_index_only: true

  # Значения по умолчанию, взятые из mkdocs_theme.yml
  language: ru
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: purple
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins